name: sms
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  dotted_border: ^2.1.0
  shared_preferences: ^2.3.2
  flutter_image_slideshow: ^0.1.6
  image_picker: ^1.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.2.11

flutter_native_splash:
  color: "#ffffff"  # Background color
  image: images/logo.png  # Path to your splash screen image
  android: true
  ios: true
  fullscreen: true  # Makes the splash screen fullscreen

flutter:
  uses-material-design: true

  assets:
     - images/

  fonts:
     - family: MyFlutterApp
       fonts:
         - asset: fonts/MyFlutterApp.ttf
